net: sched: Resolve unused variable warning
../net/sched/cls_api.c:271:19: error:
unused variable 'kind' [-Werror,-Wunused-variable]

../net/sched/cls_api.c:272:9: error:
unused variable 'name' [-Werror,-Wunused-variable]

Change-Id: Ibd852dcaa3c87aaaf85f7c5ac69b48e2acd8c8f0